### ISSUE TITLE
Create a Bitcoin Wallet

### ISSUE THREAD

**Issue by rlh2ph** [bradymadden97/cs4753-project#12]
https://bitcoin.org/en/choose-your-wallet

After, fill out form here: https://docs.google.com/forms/d/e/1FAIpQLSf7yjcV9OAhpqntjB3KeEvzOXQxFHfC41dzFeho335TkKBw6w/viewform

**Comment by bradymadden97** [comment]
using bitpay now 
merchant account: zephair.merchant@gmail.com
