### ISSUE TITLE
Create a Merchant Wallet

### ISSUE THREAD

**Issue by rlh2ph** [bradymadden97/cs4753-project#13]
Im guessing this is a straightforward procedure after we create our Bitcoin wallet. 

Possible places to look: 
BitPay -- https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0ahUKEwjF4ezH0ufWAhXH5YMKHTQVCRoQFggmMAA&url=https%3A%2F%2Fbitpay.com%2F&usg=AOvVaw25QcS7rdIhQO5igYbyerSP

How to Accept BitCoin for Small Businesses -- https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=0ahUKEwjF4ezH0ufWAhXH5YMKHTQVCRoQFggsMAE&url=https%3A%2F%2Fen.bitcoin.it%2Fwiki%2FHow_to_accept_Bitcoin%2C_for_small_businesses&usg=AOvVaw39M9xYdVSs3HjDTys7qOw6

Merchant Solutions -- https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=3&cad=rja&uact=8&ved=0ahUKEwjF4ezH0ufWAhXH5YMKHTQVCRoQFgg3MAI&url=https%3A%2F%2Fwww.bitcoin.com%2Fmerchant-solutions&usg=AOvVaw31PRlBtjnWto3whm3Rdief

THIS ISSUE NEEDS MORE INFORMATION

**Comment by bradymadden97** [comment]
see #12
