### ISSUE TITLE
Integrate BitCoin Transaction API

### ISSUE THREAD

**Issue by rlh2ph** [bradymadden97/cs4753-project#14]
Now that setup is complete, you must integrate Bitcoin Transaction API to perform a checkout of at least one item (whether it be a physical good or subscription).

APIs listed here:
https://en.bitcoin.it/wiki/How_to_accept_Bitcoin,_for_small_businesses#Merchant_Services

TAs will check to see if transaction has been recorded on the block chain.

We are allowed to convert BitCoin Price to USD as a functionality.

Helpful links:
• https://blockchain.info/
• https://blockchain.info/api/api_receive
• https://blockchain.info/api/exchange_rates_api

**Comment by bradymadden97** [comment]
API tasks:
- Create invoice from cart items
- Record invoice as order in DB
- Allow user to pay merchant account through bitpay
- Setup callback page for bitpay to hit with updates on payment processing
- Display status of orders on account page
