### ISSUE TITLE
Create Store Page

### ISSUE THREAD

**Issue by rlh2ph** [bradymadden97/cs4753-project#15]
Create a page for our store with at least one item.

I would go for just one item so far since it is easier.

Store Page should have link to a checkout page

**Comment by bradymadden97** [comment]
Store setup, need to re-populate with real items and descriptions

**Comment by rlh2ph** [comment]
Item descriptions:

Fiji Air:
Four pack of 12 oz aluminum cans filled with Zephair's premium Fiji air. New air is sourced directly from Fiji per order and is harvested with drones. Cans are factory sealed and hand checked to ensure the highest quality.

and then all of the others can follow the Fiji model if it works
