### ISSUE TITLE
Add email functionality

### ISSUE THREAD

**Issue by rlh2ph** [bradymadden97/cs4753-project#16]

**Comment by rlh2ph** [comment]
Improve your server code that is used to process a user and write to your database by adding email functionality. This can be established using PHPMailer at

https://github.com/PHPMailer/PHPMailer

**Comment by bradymadden97** [comment]
TODO: for either registration or after a purchase, we're picking after registration

**Comment by rlh2ph** [comment]
TODO: vars on heroku for security

**Comment by bradymadden97** [comment]
Completed unless we want to add email receipts upon purchase
