### ISSUE TITLE
Add Database Table

### ISSUE THREAD

**Issue by rlh2ph** [bradymadden97/cs4753-project#2]
Within myPhpAdmin interface, which comes with XAMPP (can be accessed by typing localhost/phpmyadmin into your browser) create an appropriately named table (e.g., siteUsers, currentCustomers) that includes attributes that will be used to store your customer information.

**Comment by rlh2ph** [comment]
At a minimum, the table must have appropriate columns to store a user’s name, email, address, city, state, 5-digit zip code, username (if email isn’t the username), and a hash of the password (you must not store the password as plaintext). Include any other fields that are vital to your business

**Comment by bradymadden97** [comment]
Recommended DB schema:

Local DB: cs4753_project
Tables (for now): users

"users" fields:
user_id  -- int(11) -- not null, primary key, auto incrementing
first_name -- varchar(45) -- not null
last_name -- varchar(45) -- not null
email -- varchar(60) -- not null, unique
pass -- char(255) -- not null
registration_date -- datetime
address -- varchar(60)
city -- varchar(45)
state -- varchar(45)
zip -- int(5)
last_login -- timestamp -- Default=CURRENT_TIMESTAMP

**Comment by rlh2ph** [comment]
Table is created with the fields in the above comment.
