### ISSUE TITLE
Current DB tables

### ISSUE THREAD

**Issue by bradymadden97** [bradymadden97/cs4753-project#22]
![image](https://user-images.githubusercontent.com/16962017/31894639-02f3c4f8-b7dd-11e7-84f8-c94620b9d0cc.png)

![image](https://user-images.githubusercontent.com/16962017/31894705-30933268-b7dd-11e7-8a77-74e6d375b067.png)

![image](https://user-images.githubusercontent.com/16962017/31894730-3ff05dee-b7dd-11e7-993c-2e425bac55ec.png)

![image](https://user-images.githubusercontent.com/16962017/31894756-4d35f05e-b7dd-11e7-9aaf-d3b7c9d102f5.png)

**Comment by rlh2ph** [comment]
<img width="1680" alt="screen shot 2017-10-23 at 11 36 19 am" src="https://user-images.githubusercontent.com/25697151/31898164-6ab55620-b7e6-11e7-95fe-5401a75f4438.png">

**Comment by bradymadden97** [comment]
![image](https://user-images.githubusercontent.com/16962017/32418164-90267c3a-c232-11e7-9ae7-3266a56a0f30.png)
