### ISSUE TITLE
Fix Milestone 1 Problems

### ISSUE THREAD

**Issue by rlh2ph** [bradymadden97/cs4753-project#8]
2nd pic on homescreen could change so not white text on white image 

Consider background image on signup/login for texture or imagery 

Also consider bolding some key text on about us page for focus points 

Note for MS5 - could make up own index of air cleanliness for uniqueness

**Comment by bradymadden97** [comment]
Blur new pic on homepage?
Look at text over moving images on about page and confirm it is readable
Check mobile view about page

**Comment by rlh2ph** [comment]
2nd pic on home screen is changed
Key text has been bolded for key points on about page

**Comment by bradymadden97** [comment]
need new BG pics for register and login pages

**Comment by rlh2ph** [comment]
2nd home screen picture is changed
key text is bolded on about page
new background picture has been added to sign up and login pages
